apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/Feynman3142/nd064_course_1.git
    targetRevision: HEAD
    path: project/helm/techtrends

    # helm specific config
    helm:

      # Helm values files for overriding values in the helm chart
      # The path is relative to the spec.source.path directory defined above
      valueFiles:
        - ../values-prod.yaml

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  # Sync policy
  syncPolicy: {}
