# Name of the workflow
name: "TechTrends - Package with Docker"

# Set the trigger policy
on:
  push:
    branches:
      - main

# Create the job
jobs:
  
  # Name of the job
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: curiousbee
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./project/techtrends
          file: ./project/Dockerfile
          tags: curiousbee/techtrends:latest